_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (27840, 37120)
  MAX_ITER: 46400
  WARMUP_ITERS: 1450
  CHECKPOINT_PERIOD: 2320
TEST:
  EVAL_PERIOD: 11600
VIS_PERIOD: 928
DATASETS:
  TRAIN: ('KITTI_train', 'KITTI_val')
  TEST: ('KITTI_test',)
  CATEGORY_NAMES: ('pedestrian', 'car', 'cyclist', 'van', 'truck')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 5
  STABILIZE: 0.2
OUTPUT_DIR: exp/omni3d_kitti_baseline_01
