_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (69600, 92800)
  MAX_ITER: 116000
  WARMUP_ITERS: 3625
  CHECKPOINT_PERIOD: 5800
TEST:
  EVAL_PERIOD: 29000
VIS_PERIOD: 2320
DATASETS:
  TRAIN: ('KITTI_train', 'KITTI_val')
  TEST: ('KITTI_test',)
  CATEGORY_NAMES: ('pedestrian', 'car', 'cyclist', 'van', 'truck')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 5
  STABILIZE: 0.2
OUTPUT_DIR: exp/omni3d_kitti_baseline_025