_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (278400, 371200)
  MAX_ITER: 464000
  WARMUP_ITERS: 14500
TEST:
  EVAL_PERIOD: 116000
VIS_PERIOD: 9280
DATASETS:
  TRAIN: ('ARKitScenes_train', 'ARKitScenes_val')
  TEST: ('ARKitScenes_test',)
  CATEGORY_NAMES: ('table', 'bed', 'sofa', 'television', 'refrigerator', 'chair', 'oven', 'machine', 'stove', 'shelves', 'sink', 'cabinet', 'bathtub', 'toilet')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 14
OUTPUT_DIR: exp/omni3d_arkit_baseline